spring.application.name=TarrifBuilder
server.port=8090
spring.datasource.url=jdbc:oracle:thin:@192.168.149.121:1521/ATTTEST
spring.datasource.username=IZZI_BSSSDP_QC
spring.datasource.password=IZZI_BSSSDP_QC
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.idle-timeout=5000
#spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
#spring.datasource.connectionProperties=oracle.jdbc.defaultNChar=true;charSet=ISO_1
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring_datasource.initialpoolsize=5
spring_datasource.properties.minPoolSize=5
spring_datasource.properties.maxPoolSize=5
spring_datasource.properties.maxIdleTime=5000

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

#
## DataSource Configuration for INFINET_DB
#billing_datasource_datasource.jndi-name=jdbc/INFINET_DB
#billing_datasource.url=jdbc:oracle:thin:@192.168.149.121:1521/ATTTEST
#billing_datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
#billing_datasource.properties.charSet=iso_1
#billing_datasource.username=IZZI_BSSSDP_QC
#billing_datasource.password=IZZI_BSSSDP_QC
#billing_datasource.initialpoolsize=5
#billing_datasource.properties.minPoolSize=5
#billing_datasource.properties.maxPoolSize=5
#billing_datasource.properties.maxIdleTime=5000